"""Checklist autogen service — generate a checklist document and link it as ``cargado``.

Some standard checklist requirements are marked ``permite_autogen=True`` (see the
catalog seed in ``checklist_service``): the contractor should not upload them, they
should be *generated* from the data already in the system. Today that means the two
informe reports, produced by the existing (LLM-free, fully tested) generators in
``informe_service``.

This module is the single extension seam for that behaviour: the ``_GENERADORES``
registry maps a standard requisito code to its generator + document type. To make a
new requisito autogeneratable, add one row here — nothing else changes.

The heavy lifting is reused end to end:
- generation → ``informe_service`` (validates ownership + that activities exist)
- storage + ``DocumentoFuente`` creation + checklist linking → ``document_service.upload_document``
- state transition to ``cargado`` → ``checklist_service.vincular_documento_fuente``
"""

from __future__ import annotations

import uuid
from collections.abc import Awaitable, Callable

import structlog
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions import ValidationError
from app.models.documento_cuenta_cobro import DocumentoCuentaCobro
from app.models.documento_fuente import TipoDocumentoFuente
from app.services import checklist_service, document_service, informe_service

logger = structlog.get_logger("service.checklist_autogen")

_DOCX_MEDIA_TYPE = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

# Generator signature: async (db, usuario_id, cuenta_id) -> (bytes, filename)
_Generador = Callable[[AsyncSession, uuid.UUID, uuid.UUID], Awaitable[tuple[bytes, str]]]

# Standard requisito code -> (generator, DocumentoFuente type). The keys are exactly
# the catalog codes marked ``permite_autogen=True``; registry membership IS the gate
# for "can this be autogenerated".
_GENERADORES: dict[str, tuple[_Generador, TipoDocumentoFuente]] = {
    "INFORME_ACTIVIDADES": (
        informe_service.generar_informe_actividades_docx,
        TipoDocumentoFuente.INFORME_ACTIVIDADES,
    ),
    "INFORME_SUPERVISION": (
        informe_service.generar_informe_supervision_docx,
        TipoDocumentoFuente.INFORME_SUPERVISION,
    ),
}


def es_autogenerable(requisito_codigo: str) -> bool:
    """Whether a standard requisito code can be produced by an autogenerator."""
    return requisito_codigo in _GENERADORES


async def generar_y_vincular(
    db: AsyncSession,
    usuario_id: uuid.UUID,
    cuenta_id: uuid.UUID,
    requisito_codigo: str,
) -> DocumentoCuentaCobro:
    """Generate the document for ``requisito_codigo`` and link it to the checklist row.

    The checklist row must already exist (call ``asegurar_checklist`` first).
    Raises ``ValidationError`` if the code is not autogeneratable. The generator
    itself raises ``ForbiddenError`` (ownership) or ``ValidationError`` (no activities).
    """
    entry = _GENERADORES.get(requisito_codigo)
    if entry is None:
        raise ValidationError(f"El requisito '{requisito_codigo}' no admite generación automática.")
    generador, tipo = entry

    content, filename = await generador(db, usuario_id, cuenta_id)

    # upload_document stores the bytes, creates the DocumentoFuente, derives the
    # contrato from the cuenta, and links the checklist row on the fresh path.
    resp = await document_service.upload_document(
        db,
        usuario_id,
        filename,
        content,
        _DOCX_MEDIA_TYPE,
        tipo=tipo,
        contrato_id=None,
        cuenta_cobro_id=cuenta_id,
        requisito_codigo=requisito_codigo,
    )

    # Ensure linkage idempotently: the filename is deterministic, so a regenerate
    # hits upload_document's dedup short-circuit which returns the existing document
    # WITHOUT linking. Linking again here is a no-op on the fresh path and guarantees
    # estado=CARGADO on the dedup path.
    fila = await checklist_service.vincular_documento_fuente(db, cuenta_id, requisito_codigo, resp.id)
    await db.commit()

    await logger.ainfo(
        "checklist_autogen_generado",
        cuenta_id=str(cuenta_id),
        requisito_codigo=requisito_codigo,
        documento_fuente_id=str(resp.id),
    )
    return fila
