"""Convention guard: new migrations must be idempotent against `create_all`.

`app.main.lifespan` runs `Base.metadata.create_all` BEFORE `alembic upgrade
head`, so a migration that calls `op.create_table(` / `op.create_index(` /
`op.add_column(` directly collides with what create_all already built
(`DuplicateTable`), aborts the upgrade, leaves `alembic_version` behind and every
later migration silently unapplied — production hit this with 042/043.

WHAT IS SCANNED. Only the legacy migrations (a 1-3 digit numeric prefix <= 043,
already applied everywhere) are exempt. EVERYTHING ELSE under `alembic/versions/`
is scanned: numbered files above 043 AND hash-named files such as
`9f2a1b3c4d5e_add_foo.py`, which is what `make migration` (alembic autogenerate,
default `%(rev)s_%(slug)s` template) produces. AUTOGENERATED MIGRATIONS EMIT BARE
`op.create_table` / `op.add_column` / `op.create_index` CALLS: EDIT THEM TO USE THE
HELPERS IN `app.core.migration_helpers` BEFORE MERGING (the guard fails until you do).

WHAT IS FLAGGED (AST based, so docstrings and comments never match):
  * `op.create_table`, `op.create_index`, `op.add_column`,
    `op.create_unique_constraint`, `op.create_foreign_key`, reached through any
    alias (`from alembic import op as o`, `import alembic.op as o`,
    `alembic.op.x(...)`, `from alembic.op import create_table as mk`);
  * the same creating calls made on a `op.batch_alter_table(...)` context
    (`with op.batch_alter_table("t") as b: b.add_column(...)`, or chained);
  * `op.execute(...)` whose string (plain, `text("...")`, f-string, implicit
    concatenation) contains `CREATE TABLE`, `CREATE [UNIQUE] INDEX` or
    `ADD COLUMN` without `IF NOT EXISTS`.

NOT EXHAUSTIVE. `op.create_check_constraint`, `op.create_primary_key`, PostgreSQL
enum creation and DDL built in variables or issued through `bind.execute` are NOT
detected, and there is no idempotent helper for them. A migration that needs one
must make it idempotent by hand (existence check, `DO` block) or carry an explicit
opt-out on the call line or on the comment line right above it:

    op.create_check_constraint(...)  # migration-guard: ignore <why this is safe>

The reason after `ignore` is mandatory; a bare marker does not suppress anything.
"""

from __future__ import annotations

import ast
import re
from pathlib import Path

import pytest

_VERSIONS_DIR = Path(__file__).resolve().parent.parent / "alembic" / "versions"
_LAST_GRANDFATHERED = 43
_FORBIDDEN = {
    "create_table": "create_table_if_missing",
    "create_index": "create_index_if_missing",
    "add_column": "add_column_if_missing",
    "create_unique_constraint": "create_unique_constraint_if_missing",
    "create_foreign_key": "create_foreign_key_if_missing",
}
_BATCH_FORBIDDEN = {name: helper for name, helper in _FORBIDDEN.items() if name != "create_table"}
# Legacy migrations are named `NNN_slug.py` (three digits). A longer numeric prefix,
# e.g. an all-digit 12-char revision id, is NOT a legacy number.
_LEGACY_PREFIX = re.compile(r"^(\d{1,3})_")
_HEADER = "from alembic import op\n\n\ndef upgrade() -> None:\n"
_IGNORE = re.compile(r"#\s*migration-guard:\s*ignore\s+\S+")
_RAW_DDL = re.compile(
    r"(CREATE\s+(?:UNIQUE\s+)?(?:TABLE|INDEX(?:\s+CONCURRENTLY)?)|ADD\s+COLUMN)(\s+IF\s+NOT\s+EXISTS)?",
    re.IGNORECASE,
)


def _is_legacy(name: str, last_grandfathered: int) -> bool:
    match = _LEGACY_PREFIX.match(name)
    return match is not None and int(match.group(1)) <= last_grandfathered


def _dotted(node: ast.expr) -> str | None:
    """`a.b.c` for a Name/Attribute chain, else None."""
    parts: list[str] = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if isinstance(node, ast.Name):
        parts.append(node.id)
        return ".".join(reversed(parts))
    return None


class _Scope:
    """Names in a module that refer to `alembic.op`, its functions, or a batch context."""

    def __init__(self, tree: ast.AST) -> None:
        self.op_names: set[str] = {"op"}
        self.func_aliases: dict[str, str] = {}
        self.batch_names: set[str] = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.module == "alembic":
                self.op_names.update(a.asname or a.name for a in node.names if a.name == "op")
            elif isinstance(node, ast.ImportFrom) and node.module == "alembic.op":
                for alias in node.names:
                    self.func_aliases[alias.asname or alias.name] = alias.name
            elif isinstance(node, ast.Import):
                self.op_names.update(a.asname for a in node.names if a.name == "alembic.op" and a.asname)
        for node in ast.walk(tree):
            if isinstance(node, ast.With | ast.AsyncWith):
                for item in node.items:
                    if isinstance(item.optional_vars, ast.Name) and self.is_batch_call(item.context_expr):
                        self.batch_names.add(item.optional_vars.id)
            elif isinstance(node, ast.Assign) and self.is_batch_call(node.value):
                self.batch_names.update(t.id for t in node.targets if isinstance(t, ast.Name))

    def is_op(self, node: ast.expr) -> bool:
        dotted = _dotted(node)
        return dotted is not None and (dotted in self.op_names or dotted == "alembic.op")

    def is_batch_call(self, node: ast.expr) -> bool:
        return (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "batch_alter_table"
            and self.is_op(node.func.value)
        )


def _suppressed(lines: list[str], lineno: int) -> bool:
    """Opt-out marker with a reason on the call's line, or on a comment-only line right above."""
    if _IGNORE.search(lines[lineno - 1]):
        return True
    if lineno >= 2:
        above = lines[lineno - 2].strip()
        return above.startswith("#") and _IGNORE.search(above) is not None
    return False


def _string_content(call: ast.Call) -> str:
    """Every string literal fragment inside the call's arguments (text("..."), f-strings, concatenations)."""
    return " ".join(
        n.value for arg in call.args for n in ast.walk(arg) if isinstance(n, ast.Constant) and isinstance(n.value, str)
    )


def _classify(node: ast.Call, scope: _Scope) -> str | None:
    """Return the violation label for `node`, or None when the call is fine."""
    func = node.func
    if isinstance(func, ast.Name) and func.id in scope.func_aliases:
        real = scope.func_aliases[func.id]
        if real in _FORBIDDEN:
            return f"op.{real}() -> use {_FORBIDDEN[real]}()"
        return None
    if not isinstance(func, ast.Attribute):
        return None
    if scope.is_op(func.value):
        if func.attr in _FORBIDDEN:
            return f"op.{func.attr}() -> use {_FORBIDDEN[func.attr]}()"
        if func.attr == "execute":
            bare = [m.group(1) for m in _RAW_DDL.finditer(_string_content(node)) if m.group(2) is None]
            if bare:
                return f"op.execute() runs raw DDL ({' '.join(bare[0].split()).upper()}) without IF NOT EXISTS"
        return None
    on_batch = (isinstance(func.value, ast.Name) and func.value.id in scope.batch_names) or scope.is_batch_call(
        func.value
    )
    if on_batch and func.attr in _BATCH_FORBIDDEN:
        return f"batch.{func.attr}() -> use {_BATCH_FORBIDDEN[func.attr]}()"
    return None


def find_violations(versions_dir: Path, last_grandfathered: int = _LAST_GRANDFATHERED) -> list[str]:
    """Return `file:line: <label>` for each offending call in every non-legacy migration file."""
    violations: list[str] = []
    for path in sorted(versions_dir.glob("*.py")):
        if path.name == "__init__.py" or _is_legacy(path.name, last_grandfathered):
            continue
        source = path.read_text(encoding="utf-8")
        lines = source.splitlines()
        tree = ast.parse(source, filename=str(path))
        scope = _Scope(tree)
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            label = _classify(node, scope)
            if label is not None and not _suppressed(lines, node.lineno):
                violations.append(f"{path.name}:{node.lineno}: {label}")
    return violations


def test_real_migrations_use_the_idempotent_helpers() -> None:
    assert find_violations(_VERSIONS_DIR) == [], (
        "Migrations after 043 must not call op.create_table/create_index/add_column directly: "
        "create_all runs before alembic at boot, so they collide with existing objects. "
        "Use the helpers in app.core.migration_helpers."
    )


def test_scanner_catches_real_historical_offenders_when_the_cutoff_is_lowered() -> None:
    # Proves the scanner actually sees real migration files: historical
    # migrations DO call the raw ops (e.g. 007 create_table, 039 add_column) and
    # are only exempt because of the 043 cutoff. 042 itself no longer offends
    # since it was made idempotent.
    violations = find_violations(_VERSIONS_DIR, last_grandfathered=0)

    assert any(v.startswith("007_agent_runs_borradores.py:") and "op.create_table()" in v for v in violations)
    assert any(v.startswith("039_documento_fuente_sha256.py:") and "op.add_column()" in v for v in violations)
    assert not any(v.startswith("042_paquete_job.py:") for v in violations)


class TestScannerOnSyntheticMigrations:
    @staticmethod
    def _write(tmp_path: Path, name: str, body: str) -> None:
        (tmp_path / name).write_text(body, encoding="utf-8")

    @pytest.mark.parametrize(
        ("call", "helper"),
        [
            ('op.create_table("t", sa.Column("id", sa.Integer()))', "create_table_if_missing"),
            ('op.create_index("ix_t_id", "t", ["id"])', "create_index_if_missing"),
            ('op.add_column("t", sa.Column("c", sa.Integer()))', "add_column_if_missing"),
        ],
    )
    def test_flags_each_forbidden_call_in_a_migration_after_043(self, tmp_path: Path, call: str, helper: str) -> None:
        self._write(tmp_path, "044_bad.py", "import sqlalchemy as sa\n" + _HEADER + f"    {call}\n")

        violations = find_violations(tmp_path)

        assert len(violations) == 1
        assert violations[0].startswith("044_bad.py:6:")
        assert helper in violations[0]

    def test_flags_every_offender_in_the_same_file_and_across_files(self, tmp_path: Path) -> None:
        self._write(tmp_path, "044_a.py", _HEADER + '    op.create_table("a")\n    op.add_column("a", None)\n')
        self._write(tmp_path, "150_b.py", _HEADER + '    op.create_index("i", "b", ["x"])\n')

        assert len(find_violations(tmp_path)) == 3

    def test_call_nested_in_a_helper_function_or_branch_is_still_caught(self, tmp_path: Path) -> None:
        body = (
            "from alembic import op\n\n\n"
            "def _make() -> None:\n"
            "    if True:\n"
            "        op.create_table('x')\n\n\n"
            "def upgrade() -> None:\n"
            "    _make()\n"
        )
        self._write(tmp_path, "045_nested.py", body)

        assert len(find_violations(tmp_path)) == 1

    def test_migration_using_the_helpers_passes(self, tmp_path: Path) -> None:
        body = (
            "import sqlalchemy as sa\n"
            "from app.core.migration_helpers import (\n"
            "    add_column_if_missing,\n"
            "    create_index_if_missing,\n"
            "    create_table_if_missing,\n"
            ")\n\n\n"
            "def upgrade() -> None:\n"
            '    create_table_if_missing("t", sa.Column("id", sa.Integer()))\n'
            '    create_index_if_missing("ix_t_id", "t", ["id"])\n'
            '    add_column_if_missing("t", sa.Column("c", sa.Integer()))\n'
        )
        self._write(tmp_path, "044_good.py", body)

        assert find_violations(tmp_path) == []

    def test_mentions_in_docstrings_and_comments_are_not_calls(self, tmp_path: Path) -> None:
        body = (
            '"""Replaces a bare op.create_table(...) with the helper."""\n'
            "from alembic import op\n\n\n"
            "def upgrade() -> None:\n"
            "    # op.add_column('t', c) would collide with create_all\n"
            '    op.execute("SELECT 1")\n'
            '    op.drop_table("t")\n'
        )
        self._write(tmp_path, "044_doc.py", body)

        assert find_violations(tmp_path) == []

    def test_grandfathered_migrations_up_to_043_are_ignored(self, tmp_path: Path) -> None:
        for name in ("001_base.py", "042_paquete_job.py", "043_flags.py"):
            self._write(tmp_path, name, _HEADER + '    op.create_table("t")\n')

        assert find_violations(tmp_path) == []

    def test_boundary_044_is_the_first_guarded_number(self, tmp_path: Path) -> None:
        self._write(tmp_path, "043_x.py", _HEADER + '    op.create_table("t")\n')
        self._write(tmp_path, "044_x.py", _HEADER + '    op.create_table("t")\n')

        violations = find_violations(tmp_path)

        assert [v.split(":")[0] for v in violations] == ["044_x.py"]

    def test_non_python_files_and_init_are_ignored(self, tmp_path: Path) -> None:
        self._write(tmp_path, "__init__.py", 'from alembic import op\nop.create_table("t")\n')
        self._write(tmp_path, "044_notes.txt", 'op.create_table("t")\n')
        self._write(tmp_path, "README.md", 'op.create_table("t")\n')

        assert find_violations(tmp_path) == []

    def test_hash_named_autogenerated_offender_is_flagged(self, tmp_path: Path) -> None:
        # `make migration` (alembic autogenerate, default file_template) names files
        # `<12 hex chars>_<slug>.py`. They have no numeric prefix, so a guard that
        # only scanned numbered files let the first autogenerated create_table through.
        self._write(tmp_path, "9f2a1b3c4d5e_add_foo.py", _HEADER + '    op.create_table("foo")\n')

        violations = find_violations(tmp_path)

        assert len(violations) == 1
        assert violations[0].startswith("9f2a1b3c4d5e_add_foo.py:")

    def test_hash_named_migration_using_helpers_passes(self, tmp_path: Path) -> None:
        body = (
            "from app.core.migration_helpers import create_table_if_missing\n\n\n"
            "def upgrade() -> None:\n"
            '    create_table_if_missing("foo")\n'
        )
        self._write(tmp_path, "9f2a1b3c4d5e_add_foo.py", body)

        assert find_violations(tmp_path) == []

    def test_purely_numeric_hash_is_not_mistaken_for_a_legacy_number(self, tmp_path: Path) -> None:
        # A 12-digit all-numeric revision id (possible, if rare) must not read as "revision 1".
        self._write(tmp_path, "000000000001_add_foo.py", _HEADER + '    op.create_table("foo")\n')

        assert len(find_violations(tmp_path)) == 1

    def test_empty_directory_has_no_violations(self, tmp_path: Path) -> None:
        assert find_violations(tmp_path) == []


def _scan(tmp_path: Path, body: str, name: str = "044_x.py") -> list[str]:
    (tmp_path / name).write_text(body, encoding="utf-8")
    return find_violations(tmp_path)


class TestConstraintOps:
    @pytest.mark.parametrize(
        ("call", "helper"),
        [
            ('op.create_unique_constraint("uq_t", "t", ["a"])', "create_unique_constraint_if_missing"),
            ('op.create_foreign_key("fk_t", "t", "u", ["a"], ["id"])', "create_foreign_key_if_missing"),
        ],
    )
    def test_unique_and_foreign_key_creation_is_flagged(self, tmp_path: Path, call: str, helper: str) -> None:
        violations = _scan(tmp_path, _HEADER + f"    {call}\n")

        assert len(violations) == 1
        assert helper in violations[0]

    def test_check_and_primary_key_are_a_documented_gap_not_flagged(self, tmp_path: Path) -> None:
        # Not exhaustive by design: no idempotent helper exists for these; the
        # module docstring tells the author to guard them manually or opt out.
        body = (
            _HEADER
            + '    op.create_check_constraint("ck", "t", "a > 0")\n    op.create_primary_key("pk", "t", ["a"])\n'
        )

        assert _scan(tmp_path, body) == []


class TestAliasEvasions:
    @pytest.mark.parametrize(
        "header",
        [
            "from alembic import op as o\n\n\ndef upgrade() -> None:\n",
            "import alembic.op as o\n\n\ndef upgrade() -> None:\n",
        ],
    )
    def test_aliased_op_module_is_resolved(self, tmp_path: Path, header: str) -> None:
        violations = _scan(tmp_path, header + '    o.create_table("t")\n')

        assert len(violations) == 1
        assert "create_table" in violations[0]

    def test_fully_qualified_alembic_op_is_resolved(self, tmp_path: Path) -> None:
        body = "import alembic\n\n\ndef upgrade() -> None:\n    alembic.op.add_column('t', None)\n"

        assert len(_scan(tmp_path, body)) == 1

    def test_function_imported_from_alembic_op_is_resolved_even_when_renamed(self, tmp_path: Path) -> None:
        body = "from alembic.op import create_index as mk\n\n\ndef upgrade() -> None:\n    mk('i', 't', ['a'])\n"

        violations = _scan(tmp_path, body)

        assert len(violations) == 1
        assert "create_index" in violations[0]

    def test_unrelated_object_named_like_an_op_method_is_not_flagged(self, tmp_path: Path) -> None:
        body = "class Repo:\n    def create_table(self) -> None: ...\n\n\n"
        body += "def upgrade() -> None:\n    Repo().create_table()\n"

        assert _scan(tmp_path, body) == []


class TestBatchEvasions:
    def test_batch_context_variable_calls_are_flagged(self, tmp_path: Path) -> None:
        body = (
            "from alembic import op\n\n\n"
            "def upgrade() -> None:\n"
            '    with op.batch_alter_table("t") as b:\n'
            "        b.add_column(None)\n"
            '        b.create_index("i", ["a"])\n'
            '        b.create_unique_constraint("u", ["a"])\n'
            '        b.create_foreign_key("f", "o", ["a"], ["id"])\n'
        )

        violations = _scan(tmp_path, body)

        assert len(violations) == 4
        assert all("batch" in v for v in violations)

    def test_chained_batch_call_is_flagged(self, tmp_path: Path) -> None:
        body = 'from alembic import op\n\n\ndef upgrade() -> None:\n    op.batch_alter_table("t").add_column(None)\n'

        assert len(_scan(tmp_path, body)) == 1

    def test_batch_context_via_aliased_op_and_assignment_is_flagged(self, tmp_path: Path) -> None:
        body = (
            "from alembic import op as o\n\n\n"
            "def upgrade() -> None:\n"
            '    b = o.batch_alter_table("t")\n'
            "    b.add_column(None)\n"
        )

        assert len(_scan(tmp_path, body)) == 1

    def test_batch_alter_and_drop_are_not_flagged(self, tmp_path: Path) -> None:
        body = (
            "from alembic import op\n\n\n"
            "def upgrade() -> None:\n"
            '    with op.batch_alter_table("t") as b:\n'
            '        b.alter_column("a", nullable=False)\n'
            '        b.drop_column("z")\n'
        )

        assert _scan(tmp_path, body) == []

    def test_add_column_on_an_unrelated_variable_is_not_flagged(self, tmp_path: Path) -> None:
        body = "from alembic import op\n\n\ndef upgrade() -> None:\n    table.add_column(None)\n"

        assert _scan(tmp_path, body) == []


class TestRawDdlInExecute:
    @pytest.mark.parametrize(
        "expr",
        [
            '"CREATE TABLE t (id INT)"',
            '"create table t (id int)"',
            "'CREATE INDEX ix ON t (a)'",
            '"CREATE UNIQUE INDEX ux ON t (a)"',
            '"ALTER TABLE t ADD COLUMN c INT"',
            '"alter table t add   column c int"',
            'sa.text("CREATE TABLE t (id INT)")',
            'text("""\n        CREATE INDEX ix ON t (a)\n    """)',
            '("CREATE TABLE t " "(id INT)")',
            'f"CREATE TABLE {NAME} (id INT)"',
            '"CREATE TABLE t (id INT);" "CREATE INDEX IF NOT EXISTS ix ON t (a)"',
        ],
    )
    def test_ddl_without_if_not_exists_is_flagged(self, tmp_path: Path, expr: str) -> None:
        body = "import sqlalchemy as sa\nfrom alembic import op\nNAME = 't'\n\n\ndef upgrade() -> None:\n"
        body += f"    op.execute({expr})\n"

        violations = _scan(tmp_path, body)

        assert len(violations) == 1
        assert "op.execute()" in violations[0]

    @pytest.mark.parametrize(
        "expr",
        [
            '"CREATE TABLE IF NOT EXISTS t (id INT)"',
            '"create index if not exists ix on t (a)"',
            '"CREATE UNIQUE INDEX IF NOT EXISTS ux ON t (a)"',
            '"CREATE INDEX CONCURRENTLY IF NOT EXISTS ix ON t (a)"',
            '"ALTER TABLE t ADD COLUMN IF NOT EXISTS c INT"',
            '"UPDATE requisitos_documento SET solo_primera_cuenta = TRUE"',
            '"SELECT 1"',
            'sa.text("DROP TABLE IF EXISTS t")',
        ],
    )
    def test_guarded_or_non_creating_statements_pass(self, tmp_path: Path, expr: str) -> None:
        body = "import sqlalchemy as sa\nfrom alembic import op\n\n\ndef upgrade() -> None:\n"
        body += f"    op.execute({expr})\n"

        assert _scan(tmp_path, body) == []

    def test_ddl_text_outside_op_execute_is_not_flagged(self, tmp_path: Path) -> None:
        body = '"""Explains that CREATE TABLE t is now guarded."""\nMESSAGE = "CREATE TABLE only when missing"\n'

        assert _scan(tmp_path, body) == []


class TestIgnoreMarker:
    def test_marker_with_a_reason_on_the_same_line_suppresses(self, tmp_path: Path) -> None:
        body = _HEADER + '    op.create_table("t")  # migration-guard: ignore table is created only here, no model\n'

        assert _scan(tmp_path, body) == []

    def test_marker_with_a_reason_on_the_previous_line_suppresses(self, tmp_path: Path) -> None:
        body = _HEADER + '    # migration-guard: ignore enum-backed, guarded by a DO block\n    op.create_table("t")\n'

        assert _scan(tmp_path, body) == []

    def test_marker_without_a_reason_does_not_suppress(self, tmp_path: Path) -> None:
        body = _HEADER + '    op.create_table("t")  # migration-guard: ignore\n'

        assert len(_scan(tmp_path, body)) == 1

    def test_marker_only_covers_its_own_call(self, tmp_path: Path) -> None:
        body = _HEADER + '    op.create_table("a")  # migration-guard: ignore reason\n    op.create_table("b")\n'

        violations = _scan(tmp_path, body)

        assert len(violations) == 1
        assert violations[0].startswith("044_x.py:6:")
