"""Pydantic schemas for per-cuenta custom/inferred requirements."""

from __future__ import annotations

import uuid
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

# Checklist build mode chosen at the post-creation gate.
RequisitosModo = Literal["estandar", "augment", "reemplazar"]


# ── LLM structured output (response_format) ──────────────────────────────────


class RequisitoInferidoLLM(BaseModel):
    """One requirement inferred by the LLM from a requirements document/text."""

    codigo: str = ""
    etiqueta: str = ""
    descripcion: str = ""
    obligatorio: bool = True
    solo_primera_cuenta: bool = False
    keywords_deteccion: list[str] = Field(default_factory=list)
    mapea_a_estandar: str | None = None


class RequisitosInferidosLLM(BaseModel):
    """Top-level wrapper for the structured list of inferred requirements."""

    requisitos: list[RequisitoInferidoLLM] = Field(default_factory=list)


# ── Structured extraction (billing-resilience-templates, slice #7) ──────────
#
# Richer LLM output than `RequisitoInferidoLLM`: adds `categoria` (free-text
# grouping, e.g. "identificacion", "seguridad_social", "informes") and
# `permite_autogen` (whether this requisito's document could plausibly be
# autogenerated, mirroring the standard catalog's `RequisitoDocumento.
# permite_autogen` column) on top of the existing `solo_primera_cuenta` flag.
# Neither `categoria` nor `permite_autogen` is persisted — this slice adds NO
# migration; `RequisitoCuenta` has no columns for them. They exist purely to
# enrich the non-persisted preview (grouping/highlighting in the review UI)
# before the user applies a subset via the EXISTING `POST /definir`
# (`DefinirRequisitosBody` -> `RequisitoCuentaItem`, unchanged).


class RequisitoEstructuradoLLM(RequisitoInferidoLLM):
    """One requirement inferred by the LLM, with structured fields.

    Subclasses `RequisitoInferidoLLM` (rather than duplicating its fields) so
    `_map_a_estandar` — typed against the base class — accepts either shape
    unchanged (Liskov-safe reuse of the exact same catalog-mapping logic).
    """

    categoria: str = ""
    permite_autogen: bool = False


class RequisitosEstructuradosLLM(BaseModel):
    """Top-level wrapper for the structured-extraction LLM output."""

    requisitos: list[RequisitoEstructuradoLLM] = Field(default_factory=list)


# ── API request / response ───────────────────────────────────────────────────


class RequisitoCuentaItem(BaseModel):
    """An editable requirement row (preview or persisted custom set).

    ``id`` is present only for already-persisted custom requisitos; it is None
    for freshly inferred items that have not been applied yet.
    """

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID | None = None
    codigo: str
    etiqueta: str
    descripcion: str | None = None
    obligatorio: bool = True
    solo_primera_cuenta: bool = False
    tipo_documento_fuente: str | None = None
    keywords_deteccion: list[str] = Field(default_factory=list)
    orden: int = 500
    mapea_a_estandar: str | None = None
    origen: str = "inferido"


class InferirTextoBody(BaseModel):
    """Request body to infer requirements from pasted text."""

    texto: str = Field(min_length=1, max_length=200_000)


class RequisitosInferidosPreview(BaseModel):
    """Non-persisted preview returned by the inference endpoints."""

    requisitos: list[RequisitoCuentaItem] = Field(default_factory=list)
    avisos: list[str] = Field(default_factory=list)


class RequisitoEstructuradoItem(RequisitoCuentaItem):
    """A structured, editable requirement row — superset of `RequisitoCuentaItem`
    with `categoria` and `permite_autogen`. Not persisted as-is: applying the
    reviewed set still goes through the existing `POST /definir`
    (`DefinirRequisitosBody`), which only understands the base
    `RequisitoCuentaItem` fields (no migration in this slice)."""

    categoria: str = ""
    permite_autogen: bool = False


class RequisitosEstructuradosPreview(BaseModel):
    """Non-persisted structured preview — extends `RequisitosInferidosPreview`
    with `categoria`/`permite_autogen` per item (billing-resilience-templates,
    slice #7)."""

    requisitos: list[RequisitoEstructuradoItem] = Field(default_factory=list)
    avisos: list[str] = Field(default_factory=list)


class DefinirRequisitosBody(BaseModel):
    """Apply action: replace the cuenta's custom set and set the build mode."""

    modo: RequisitosModo
    requisitos: list[RequisitoCuentaItem] = Field(default_factory=list)


class RequisitosCuentaSet(BaseModel):
    """Current custom set + build mode for a cuenta (for re-editing)."""

    modo: RequisitosModo | None = None
    requisitos: list[RequisitoCuentaItem] = Field(default_factory=list)
