"""RequisitoDocumento — catalog of required documents for a cuenta de cobro.

Seeded via migration 011. Extensible per entidad territorial without redeploy.
"""

from __future__ import annotations

from sqlalchemy import Boolean, Integer, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base
from app.models.base import TimestampMixin


class RequisitoDocumento(TimestampMixin, Base):
    __tablename__ = "requisitos_documento"

    codigo: Mapped[str] = mapped_column(String(50), primary_key=True)
    etiqueta: Mapped[str] = mapped_column(String(200), nullable=False)
    descripcion: Mapped[str | None] = mapped_column(Text, nullable=True)
    obligatorio: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    solo_primera_cuenta: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False,
        comment="If True, only required for the first cuenta de cobro of the contrato.",
    )
    permite_autogen: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False,
        comment="If True, this document can be auto-generated by the agent in a future phase.",
    )
    tipo_documento_fuente: Mapped[str | None] = mapped_column(
        String(50), nullable=True,
        comment="Maps to TipoDocumentoFuente enum value for uploads.",
    )
    keywords_deteccion: Mapped[list[str]] = mapped_column(
        JSON, nullable=False, default=list,
        comment="Lowercase keywords used to match SecopDocumento.nombre_archivo / descripcion.",
    )
    orden: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
